### PR TITLE
added product based companies in Kolkata

### PR DESCRIPTION
**Pull request by anirbandas18**
…places in India

### Please make sure you check all the items.

- [x] The numbering of the company that you added starts with ```1```.
- [x] You have increased the ```Total Companies Added``` count.

### CODE REVIEW

**Comment by Kaustubh-Natuskar** [comment]
@anirbandas18   Are you sure they all are pbc's?

**Comment by anirbandas18** [comment]
Yes

**Comment by anirbandas18** [comment]
Check this My answer to What are the good product-based software companies in Kolkata? https://www.quora.com/What-are-the-good-product-based-software-companies-in-Kolkata/answer/Anirban-Das-367?ch=15&oid=168763351&share=271bd8f7&srid=dEcC&target_type=answer

**Comment by Kaustubh-Natuskar** [comment]
Great. Thank you but i merged a different pr, so now yours will cause merge conflicts. Kindly change the count. 
Thank you

**Review by Kaustubh-Natuskar — CHANGES_REQUESTED** [review]
Change the count. According to latest main

**Comment by Kaustubh-Natuskar** [comment]
@anirbandas18  hey buddy can you please change according to latest changes?

**Comment by Kaustubh-Natuskar** [comment]
closing due to no activity from @anirbandas18

**Comment by anirbandas18** [comment]
Ok

**Pull request closed without merging**
