### PR TITLE
Added a new company "Planful", decent company with good package and reviews on glassdoor.

### PR DESCRIPTION
**Pull request by mehul1011**
### Please make sure you check all the items.

- [x] The numbering of the company that you added starts with ```1```.
- [x] You have increased the ```Total Companies Added``` count.

### CODE REVIEW

**Comment by Kaustubh-Natuskar** [comment]
Thanks man
Why is it having 404 additions 🙂, I'm not able to open that much on mobile.

**Comment by mehul1011** [comment]
So basically it's just some indentation thing that happened because i used a prettier extension on VScode.
You can check it later when you are on the desktop, nothing is leading to any bug or anything i am sure.

**Comment by Kaustubh-Natuskar** [comment]
Great But it has deleted the spaces after a company section it will fine locally but on web and markdown it'll not generate new line so everything will be on same line. Please add two spaces after each section for example
1.  [Benchmark](https://benchmarkit.zohorecruit.com/jobs/Careers)<two spaces>
This helps putting us a new line below. Don't use any extensions

Thank you for contributing :)

**Comment by mehul1011** [comment]
Oh okay, makes sense
But instead of 2 spaces, can we use something else to work around?
Like '\n' or something, because later someone will come up with this problem again.

**Comment by mehul1011** [comment]
Can you check out my forked repo (https://github.com/mehul1011/moreThanFAANGM?organization=mehul1011&organization=mehul1011)

Things seem to be fine.

**Review by Kaustubh-Natuskar — APPROVED** [review]

**Pull request closed without merging**
